name: Deploy to Development

# Only one workflow in a concurrency group may run at a time
concurrency:
  group: development-concurrency
  cancel-in-progress: true

on:
  push:
    branches:
      - "main"

jobs:
  trigger-github-deployment:
    name: Trigger GitHub Deployment
    environment: Development
    runs-on: ubuntu-latest
    steps:
      - name: Empty Step
        run: echo "Hello World"

  get-short-sha:
    needs: trigger-github-deployment
    outputs:
      tag: ${{ steps.get-tag.outputs.tag }}
    runs-on: ubuntu-latest
    steps:
      - id: get-tag
        run: |
          SHA_SHORT=$(echo ${{ github.sha }} | cut -c1-8)
          echo "tag=$SHA_SHORT" >> "$GITHUB_OUTPUT"

  build-and-push-components:
    name: Build and push containers to acr for Development
    needs: trigger-github-deployment
    uses: ./.github/workflows/publish_component.yml
    with:
      Registry: auroradevacr.azurecr.io
      ImageName: robotics/inspection-data-analyzer
      Tag: ${{ needs.get-short-sha.outputs.tag }}
    secrets:
      RegistryUsername: ${{ secrets.ROBOTICS_AURORADEVACR_USERNAME }}
      RegistryPassword: ${{ secrets.ROBOTICS_AURORADEVACR_PASSWORD }}

  deploy:
    name: Update deployment in Development
    needs: [build-and-push-components, get-short-sha, trigger-github-deployment]
    uses: ./.github/workflows/update_aurora_deployment.yml
    with:
      Environment: development
      Registry: auroraprodacr.azurecr.io
      ImageName: ${{ github.repository }}
      # Add dev. prefix for the tags used in dev environment,
      # due to the commit hash can be interpreted as an integer if only numbers
      # PS: Needs to match build-and-push-components.with.Tag
      Tag: "dev.${{ needs.get-short-sha.outputs.tag }}"
      AuthorEmail: ${{ github.event.head_commit.author.email }}
      AuthorName: ${{ github.event.head_commit.author.name }}
    secrets:
      DeployKey: ${{ secrets.ANALYTICS_INFRASTRUCTURE_DEPLOY_KEY }}
